import type { PricingRecordDraftInput } from "./pricing-registry"

type SeedRow = Omit<PricingRecordDraftInput, "effectiveTime" | "observedTime" | "supersededTime" | "enabled"> & {
  id: string
}

function perToken(sourceType: SeedRow["sourceType"], sourceUrl: string) {
  return { kind: "per_token" as const, provenance: { sourceType, sourceUrl } }
}

function includedInOutput(sourceType: SeedRow["sourceType"], sourceUrl: string) {
  return { kind: "included_in_output" as const, provenance: { sourceType, sourceUrl } }
}

export const CURRENT_EFFECTIVE_PRICING_SEED: SeedRow[] = [
  {
    id: "google:gemini-2.5-pro",
    canonicalVendor: "google",
    canonicalModel: "gemini-2.5-pro",
    vendorModelId: "gemini-2.5-pro",
    currency: "USD",
    inputPrice: 1.25,
    outputPrice: 10,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://ai.google.dev/gemini-api/docs/pricing"),
    cacheReadPrice: 0.125,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://ai.google.dev/gemini-api/docs/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "google:gemini-3-flash-preview",
    canonicalVendor: "google",
    canonicalModel: "gemini-3-flash-preview",
    vendorModelId: "gemini-3-flash-preview",
    currency: "USD",
    inputPrice: 0.5,
    outputPrice: 3,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://ai.google.dev/gemini-api/docs/pricing"),
    cacheReadPrice: 0.05,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://ai.google.dev/gemini-api/docs/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "google:gemini-3-pro-preview",
    canonicalVendor: "google",
    canonicalModel: "gemini-3-pro-preview",
    vendorModelId: "gemini-3-pro-preview",
    currency: "USD",
    inputPrice: 2,
    outputPrice: 12,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://docs.cloud.google.com/vertex-ai/generative-ai/pricing"),
    cacheReadPrice: 0.2,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://docs.cloud.google.com/vertex-ai/generative-ai/pricing",
    confidence: "medium",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.1-codex-mini",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.1-codex-mini",
    vendorModelId: "gpt-5.1-codex-mini",
    currency: "USD",
    inputPrice: 0.25,
    outputPrice: 2,
    reasoningPrice: 2,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/models/gpt-5.1-codex-mini"),
    cacheReadPrice: 0.025,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.1-codex-mini",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.2",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.2",
    vendorModelId: "gpt-5.2",
    currency: "USD",
    inputPrice: 1.75,
    outputPrice: 14,
    reasoningPrice: 14,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/pricing"),
    cacheReadPrice: 0.175,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    confidence: "medium",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.2-codex",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.2-codex",
    vendorModelId: "gpt-5.2-codex",
    currency: "USD",
    inputPrice: 1.75,
    outputPrice: 14,
    reasoningPrice: 14,
    reasoningBillingRule: perToken("official", "https://platform.openai.com/docs/models/gpt-5.2-codex"),
    cacheReadPrice: 0.175,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://platform.openai.com/docs/models/gpt-5.2-codex",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.3-codex",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.3-codex",
    vendorModelId: "gpt-5.3-codex",
    currency: "USD",
    inputPrice: 1.75,
    outputPrice: 14,
    reasoningPrice: 14,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/pricing"),
    cacheReadPrice: 0.175,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.4",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.4",
    vendorModelId: "gpt-5.4",
    currency: "USD",
    inputPrice: 2.5,
    outputPrice: 15,
    reasoningPrice: 15,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/pricing"),
    cacheReadPrice: 0.25,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.4-fast",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.4-fast",
    vendorModelId: "gpt-5.4-fast",
    currency: "USD",
    inputPrice: 5,
    outputPrice: 30,
    reasoningPrice: 30,
    reasoningBillingRule: perToken("official", "https://openai.com/api-priority-processing/"),
    cacheReadPrice: 0.5,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://openai.com/api-priority-processing/",
    confidence: "medium",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.4-mini",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.4-mini",
    vendorModelId: "gpt-5.4-mini",
    currency: "USD",
    inputPrice: 0.75,
    outputPrice: 4.5,
    reasoningPrice: 4.5,
    reasoningBillingRule: perToken("official", "https://platform.openai.com/docs/models/gpt-5.4-mini"),
    cacheReadPrice: 0.075,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://platform.openai.com/docs/models/gpt-5.4-mini",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "zhipuai-coding-plan:glm-5.1",
    canonicalVendor: "zhipuai-coding-plan",
    canonicalModel: "glm-5.1",
    vendorModelId: "glm-5.1",
    currency: "USD",
    inputPrice: 1.4,
    outputPrice: 4.4,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://docs.z.ai/guides/overview/pricing"),
    cacheReadPrice: 0.26,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://docs.z.ai/guides/overview/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.5",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.5",
    vendorModelId: "gpt-5.5",
    currency: "USD",
    inputPrice: 5,
    outputPrice: 30,
    reasoningPrice: 30,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/pricing"),
    cacheReadPrice: 0.5,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.5-pro",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.5-pro",
    vendorModelId: "gpt-5.5-pro",
    currency: "USD",
    inputPrice: 30,
    outputPrice: 180,
    reasoningPrice: 180,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/pricing"),
    cacheReadPrice: 0,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.6-sol",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.6-sol",
    vendorModelId: "gpt-5.6-sol",
    currency: "USD",
    inputPrice: 5,
    outputPrice: 30,
    reasoningPrice: 30,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/models/gpt-5.6-sol"),
    cacheReadPrice: 0.5,
    cacheWritePrice: 6.25,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.6-terra",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.6-terra",
    vendorModelId: "gpt-5.6-terra",
    currency: "USD",
    inputPrice: 2.5,
    outputPrice: 15,
    reasoningPrice: 15,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/models/gpt-5.6-terra"),
    cacheReadPrice: 0.25,
    cacheWritePrice: 3.125,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "openai:gpt-5.6-luna",
    canonicalVendor: "openai",
    canonicalModel: "gpt-5.6-luna",
    vendorModelId: "gpt-5.6-luna",
    currency: "USD",
    inputPrice: 1,
    outputPrice: 6,
    reasoningPrice: 6,
    reasoningBillingRule: perToken("official", "https://developers.openai.com/api/docs/models/gpt-5.6-luna"),
    cacheReadPrice: 0.1,
    cacheWritePrice: 1.25,
    sourceType: "official",
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "anthropic:claude-opus-4-7",
    canonicalVendor: "anthropic",
    canonicalModel: "claude-opus-4-7",
    vendorModelId: "claude-opus-4-7",
    currency: "USD",
    inputPrice: 5,
    outputPrice: 25,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://claude.com/pricing"),
    cacheReadPrice: 0.5,
    cacheWritePrice: 6.25,
    sourceType: "official",
    sourceUrl: "https://claude.com/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "anthropic:claude-sonnet-4-6",
    canonicalVendor: "anthropic",
    canonicalModel: "claude-sonnet-4-6",
    vendorModelId: "claude-sonnet-4-6",
    currency: "USD",
    inputPrice: 3,
    outputPrice: 15,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://claude.com/pricing"),
    cacheReadPrice: 0.3,
    cacheWritePrice: 3.75,
    sourceType: "official",
    sourceUrl: "https://claude.com/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "anthropic:claude-opus-4-8",
    canonicalVendor: "anthropic",
    canonicalModel: "claude-opus-4-8",
    vendorModelId: "claude-opus-4-8",
    currency: "USD",
    inputPrice: 5,
    outputPrice: 25,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://claude.com/pricing"),
    cacheReadPrice: 0.5,
    cacheWritePrice: 6.25,
    sourceType: "official",
    sourceUrl: "https://claude.com/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    // Introductory API pricing through 2026-08-31; official standard pricing is $3 input / $15 output afterward.
    id: "anthropic:claude-sonnet-5",
    canonicalVendor: "anthropic",
    canonicalModel: "claude-sonnet-5",
    vendorModelId: "claude-sonnet-5",
    currency: "USD",
    inputPrice: 2,
    outputPrice: 10,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://claude.com/pricing"),
    cacheReadPrice: 0.2,
    cacheWritePrice: 2.5,
    sourceType: "official",
    sourceUrl: "https://claude.com/pricing",
    confidence: "high",
    isManualOverride: false,
  },
  {
    id: "kimi:kimi-2.6",
    canonicalVendor: "kimi",
    canonicalModel: "kimi-2.6",
    vendorModelId: "kimi-2.6",
    currency: "USD",
    inputPrice: 0.95,
    outputPrice: 4,
    reasoningPrice: 0,
    reasoningBillingRule: includedInOutput("official", "https://platform.kimi.ai/docs/pricing/chat-k26"),
    cacheReadPrice: 0.16,
    cacheWritePrice: 0,
    sourceType: "official",
    sourceUrl: "https://platform.kimi.ai/docs/pricing/chat-k26",
    confidence: "high",
    isManualOverride: false,
  },
]

export function materializeCurrentEffectivePricingSeed(now: number): PricingRecordDraftInput[] {
  return CURRENT_EFFECTIVE_PRICING_SEED.map((row) => ({
    ...row,
    effectiveTime: now,
    observedTime: now,
    supersededTime: null,
    enabled: true,
  }))
}
